#!/bin/sh
set -e

if [ "$GUTENBERG_SSL_ENABLE" != "1" ]; then
    cat > /tmp/gutenberg-servers.conf <<'EOF'
server {
    listen 80;

    # Log format for untrusted proxy errors is defined at http level (generated by entrypoint script)
    # Use conditional access log based on $is_trusted_proxy value
    access_log /dev/stderr gutenberg_untrusted_proxy if=$is_not_trusted_proxy;

    # `$is_trusted_proxy` and `$is_not_trusted_proxy` are defined
    # in the `10-gutenberg-trusted-proxies.conf` file generated at runtime
    # by the `40-configure-trusted-proxies.sh` entrypoint script.
    #
    # This check rejects requests from IP addresses not listed in the
    # `GUTENBERG_TRUSTED_PROXY_IPS` environment variables.
    if ($is_trusted_proxy = 0) {
        # Returns a plain 400 Bad Request response to avoid leaking network configuration details
        return 400;
    }

    include /etc/nginx/gutenberg-locations.d/*.conf;
}
EOF

    cat /tmp/gutenberg-geo.conf /tmp/gutenberg-servers.conf > /etc/nginx/conf.d/gutenberg.conf
    rm /tmp/gutenberg-geo.conf /tmp/gutenberg-servers.conf

    echo "INFO: SSL disabled. Nginx listening on HTTP port 80 only." >&2
    exit 0
fi

if [ -z "$GUTENBERG_SSL_CERT_PATH" ]; then
    echo "ERROR: GUTENBERG_SSL_ENABLE is set but GUTENBERG_SSL_CERT_PATH is not configured." >&2
    echo "You must specify the path to the SSL certificate file inside the container." >&2
    echo "Example: GUTENBERG_SSL_CERT_PATH=/etc/ssl/certs/gutenberg.crt" >&2
    echo "See: https://ksiuj.github.io/gutenberg/admin/docker.html#ssl-tls-configuration" >&2
    exit 1
fi

if [ -z "$GUTENBERG_SSL_KEY_PATH" ]; then
    echo "ERROR: GUTENBERG_SSL_ENABLE is set but GUTENBERG_SSL_KEY_PATH is not configured." >&2
    echo "You must specify the path to the SSL private key file inside the container." >&2
    echo "Example: GUTENBERG_SSL_KEY_PATH=/etc/ssl/certs/gutenberg.key" >&2
    echo "See: https://ksiuj.github.io/gutenberg/admin/docker.html#ssl-tls-configuration" >&2
    exit 1
fi

if [ ! -f "$GUTENBERG_SSL_CERT_PATH" ]; then
    echo "ERROR: SSL certificate file not found: $GUTENBERG_SSL_CERT_PATH" >&2
    echo "Ensure the certificate file is mounted via Docker volumes." >&2
    exit 1
fi

if [ ! -r "$GUTENBERG_SSL_CERT_PATH" ]; then
    echo "ERROR: SSL certificate file exists but is not readable: $GUTENBERG_SSL_CERT_PATH" >&2
    echo "Check file permissions (should be at least 644)." >&2
    exit 1
fi

if [ ! -f "$GUTENBERG_SSL_KEY_PATH" ]; then
    echo "ERROR: SSL private key file not found: $GUTENBERG_SSL_KEY_PATH" >&2
    echo "Ensure the private key file is mounted via Docker volumes." >&2
    exit 1
fi

if [ ! -r "$GUTENBERG_SSL_KEY_PATH" ]; then
    echo "ERROR: SSL private key file exists but is not readable: $GUTENBERG_SSL_KEY_PATH" >&2
    echo "Check file permissions (should be at least 600)." >&2
    exit 1
fi

: "${GUTENBERG_SSL_PORT:=443}"
: "${GUTENBERG_SSL_PROTOCOLS:=TLSv1.2 TLSv1.3}"
: "${GUTENBERG_SSL_HSTS_MAX_AGE:=31536000}"

if ! echo "$GUTENBERG_SSL_PORT" | grep -Eq '^[0-9]+$' || [ "$GUTENBERG_SSL_PORT" -lt 1 ] || [ "$GUTENBERG_SSL_PORT" -gt 65535 ]; then
    echo "ERROR: GUTENBERG_SSL_PORT must be a number between 1 and 65535, got: $GUTENBERG_SSL_PORT" >&2
    exit 1
fi

for proto in $GUTENBERG_SSL_PROTOCOLS; do
    case "$proto" in
        TLSv1.2|TLSv1.3) ;;
        *)
            echo "ERROR: Unsupported SSL protocol: $proto. Only TLSv1.2 and TLSv1.3 are supported." >&2
            echo "Current value: GUTENBERG_SSL_PROTOCOLS='$GUTENBERG_SSL_PROTOCOLS'" >&2
            exit 1
            ;;
    esac
done

cat > /tmp/gutenberg-servers.conf <<EOF
server {
    listen ${GUTENBERG_SSL_PORT} ssl;

    ssl_certificate ${GUTENBERG_SSL_CERT_PATH};
    ssl_certificate_key ${GUTENBERG_SSL_KEY_PATH};
    ssl_protocols ${GUTENBERG_SSL_PROTOCOLS};
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
EOF

if [ -n "$GUTENBERG_SSL_CIPHERS" ]; then
    cat >> /tmp/gutenberg-servers.conf <<EOF
    ssl_ciphers ${GUTENBERG_SSL_CIPHERS};
EOF
fi

if [ "$GUTENBERG_SSL_HSTS_ENABLE" = "1" ]; then
    HSTS_HEADER="max-age=${GUTENBERG_SSL_HSTS_MAX_AGE}"

    if [ "$GUTENBERG_SSL_HSTS_INCLUDE_SUBDOMAINS" = "1" ]; then
        HSTS_HEADER="${HSTS_HEADER}; includeSubDomains"
    fi

    if [ "$GUTENBERG_SSL_HSTS_PRELOAD" = "1" ]; then
        HSTS_HEADER="${HSTS_HEADER}; preload"
    fi

    cat >> /tmp/gutenberg-servers.conf <<EOF
    add_header Strict-Transport-Security "${HSTS_HEADER}" always;
EOF
fi

cat >> /tmp/gutenberg-servers.conf <<'EOF'

    # Log format for untrusted proxy errors is defined at http level (generated by entrypoint script)
    # Use conditional access log based on $is_trusted_proxy value
    access_log /dev/stderr gutenberg_untrusted_proxy if=$is_not_trusted_proxy;

    # `$is_trusted_proxy` and `$is_not_trusted_proxy` are defined
    # in the `10-gutenberg-trusted-proxies.conf` file generated at runtime
    # by the `40-configure-trusted-proxies.sh` entrypoint script.
    #
    # This check rejects requests from IP addresses not listed in the
    # `GUTENBERG_TRUSTED_PROXY_IPS` environment variables.
    if ($is_trusted_proxy = 0) {
        # Returns a plain 400 Bad Request response to avoid leaking network configuration details
        return 400;
    }

    include /etc/nginx/gutenberg-locations.d/*.conf;
}
EOF

if [ "$GUTENBERG_SSL_REDIRECT_HTTP" = "1" ]; then
    cat >> /tmp/gutenberg-servers.conf <<'EOF'

server {
    listen 80;

    # Log format for untrusted proxy errors is defined at http level (generated by entrypoint script)
    # Use conditional access log based on $is_trusted_proxy value
    access_log /dev/stderr gutenberg_untrusted_proxy if=$is_not_trusted_proxy;

    # `$is_trusted_proxy` and `$is_not_trusted_proxy` are defined
    # in the `10-gutenberg-trusted-proxies.conf` file generated at runtime
    # by the `40-configure-trusted-proxies.sh` entrypoint script.
    #
    # This check rejects requests from IP addresses not listed in the
    # `GUTENBERG_TRUSTED_PROXY_IPS` environment variables.
    if ($is_trusted_proxy = 0) {
        # Returns a plain 400 Bad Request response to avoid leaking network configuration details
        return 400;
    }

    return 301 https://$host$request_uri;
}
EOF
    echo "INFO: SSL enabled on port ${GUTENBERG_SSL_PORT}. HTTP requests on port 80 will redirect to HTTPS." >&2
else
    cat >> /tmp/gutenberg-servers.conf <<'EOF'

server {
    listen 80;

    # Log format for untrusted proxy errors is defined at http level (generated by entrypoint script)
    # Use conditional access log based on $is_trusted_proxy value
    access_log /dev/stderr gutenberg_untrusted_proxy if=$is_not_trusted_proxy;

    # `$is_trusted_proxy` and `$is_not_trusted_proxy` are defined
    # in the `10-gutenberg-trusted-proxies.conf` file generated at runtime
    # by the `40-configure-trusted-proxies.sh` entrypoint script.
    #
    # This check rejects requests from IP addresses not listed in the
    # `GUTENBERG_TRUSTED_PROXY_IPS` environment variables.
    if ($is_trusted_proxy = 0) {
        # Returns a plain 400 Bad Request response to avoid leaking network configuration details
        return 400;
    }

    include /etc/nginx/gutenberg-locations.d/*.conf;
}
EOF
    echo "INFO: SSL enabled on port ${GUTENBERG_SSL_PORT}. HTTP port 80 also serves content (no redirect)." >&2
fi

cat /tmp/gutenberg-geo.conf /tmp/gutenberg-servers.conf > /etc/nginx/conf.d/gutenberg.conf
rm /tmp/gutenberg-geo.conf /tmp/gutenberg-servers.conf

echo "INFO: SSL certificate: ${GUTENBERG_SSL_CERT_PATH}" >&2
echo "INFO: SSL protocols: ${GUTENBERG_SSL_PROTOCOLS}" >&2

if [ "$GUTENBERG_SSL_HSTS_ENABLE" = "1" ]; then
    echo "INFO: HSTS enabled with max-age=${GUTENBERG_SSL_HSTS_MAX_AGE}" >&2
fi
