services:
  db:
    image: postgres:17.6-alpine3.22
    container_name: gutenberg-db
    environment:
      POSTGRES_USER: gutenberg
      POSTGRES_DB: gutenberg
      POSTGRES_PASSWORD_FILE: /run/secrets/gutenberg_postgres_password
    volumes:
      - gutenberg_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U gutenberg -d gutenberg" ]
      interval: 1s
      retries: 10
      timeout: 5s
    secrets:
      - gutenberg_postgres_password

  redis:
    image: redis:8.2-alpine3.22
    container_name: gutenberg-redis
    restart: unless-stopped

  backend:
    # Use published image instead of building from source
    image: ghcr.io/ksiuj/gutenberg-backend:main
    container_name: gutenberg-backend
    volumes:
      - gutenberg_backend_logs:/var/log/gutenberg
      - gutenberg_backend_data:/var/lib/gutenberg
      # Expect docker_settings.py to be in the same directory as compose.yml
      - type: bind
        source: ./docker_settings.py
        target: /etc/gutenberg/docker_settings.py
        read_only: true
      - type: bind
        source: /run/cups/cups.sock
        target: /run/cups/cups.sock
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped
    secrets:
      - gutenberg_postgres_password
      - gutenberg_django_secret_key

  celery:
    # Use published image instead of building from source
    image: ghcr.io/ksiuj/gutenberg-celery:main
    container_name: gutenberg-celery
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - gutenberg_backend_logs:/var/log/gutenberg
      - gutenberg_backend_data:/var/lib/gutenberg
      # Expect docker_settings.py to be in the same directory as compose.yml
      - type: bind
        source: ./docker_settings.py
        target: /etc/gutenberg/docker_settings.py
        read_only: true
      - type: bind
        source: /run/cups/cups.sock
        target: /run/cups/cups.sock
    restart: unless-stopped
    secrets:
      - gutenberg_postgres_password
      - gutenberg_django_secret_key
    cap_add:
      - SYS_ADMIN
    privileged: true

  proxy:
    # Use published image instead of building from source
    image: ghcr.io/ksiuj/gutenberg-proxy:main
    container_name: gutenberg-proxy
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  gutenberg_postgres_data:
  gutenberg_backend_logs:
  gutenberg_backend_data:

secrets:
  gutenberg_postgres_password:
    file: ./secrets/postgres_password.txt
  gutenberg_django_secret_key:
    file: ./secrets/django_secret_key.txt