services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: gutenbergdb
      POSTGRES_USER: gutenberguser
      POSTGRES_PASSWORD: gutenbergpass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: gutenberg-redis

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: run_backend
    container_name: gutenberg-backend
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - backend_logs:/var/log/gutenberg
      - type: bind
        source: ./backend/gutenberg/settings/docker_settings.py
        target: /app/backend/gutenberg/settings/docker_settings.py
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile
      target: run_celery
    depends_on:
      - redis
      - db
    volumes:
      - backend_logs:/var/log/gutenberg
      - type: bind
        source: ./backend/gutenberg/settings/docker_settings.py
        target: /app/backend/gutenberg/settings/docker_settings.py

  proxy:
    build:
      context: .
      dockerfile: Dockerfile
      target: run_nginx
    container_name: gutenberg-proxy
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  db_data:
  backend_logs:
