services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: gutenbergdb
      POSTGRES_USER: gutenberguser
      POSTGRES_PASSWORD: gutenbergpass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: gutenberg-redis
    # ports:
    #   - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: run_server
    container_name: gutenberg-backend
    ports:
      # TODO: Disable direct Django access, all requests should go through Nginx
      - "8000:8000"
    environment:
      # - DJANGO_SETTINGS_MODULE=gutenberg.settings.gutenberg_settings
      - REDIS_URL=redis://redis:6379
    volumes:
      - backend_logs:/var/log/gutenberg
      - type: bind
        source: ./backend/gutenberg/settings/docker_settings.py
        target: /app/backend/gutenberg/settings/docker_settings.py
    depends_on:
      - db
      - redis
    command: >
      sh -c "
        uv run python manage.py migrate &&
        uv run gunicorn gutenberg.wsgi:application --bind 0.0.0.0:8000 --access-logfile -
      "
    # --access-logfile - is for debug
  celery:
    build:
      context: .
      dockerfile: Dockerfile
      target: run_server
    command: uv run celery -A gutenberg worker -l INFO
    depends_on:
      - redis
      - db
    volumes:
      - backend_logs:/var/log/gutenberg
      - type: bind
        source: ./backend/gutenberg/settings/docker_settings.py
        target: /app/backend/gutenberg/settings/docker_settings.py
    # environment:
      # - DJANGO_SETTINGS_MODULE=gutenberg.settings.docker_settings
      # - REDIS_URL=redis://redis:6379/0

  proxy:
    build:
      context: .
      dockerfile: Dockerfile
      target: run_nginx
    container_name: gutenberg-proxy
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      # TODO: Remove or move to the build_webapp build? NGINX doesn't use Node.js
      - NODE_OPTIONS=--openssl-legacy-provider

volumes:
  postgres_data:
  db_data:
  backend_logs:
