location / {
    proxy_pass http://gutenberg-backend:8000;

    # [`USE_X_FORWARDED_HOST`](https://docs.djangoproject.com/en/6.0/ref/settings/#use-x-forwarded-host)
    # is enabled in `backend/gutenberg/settings/docker_base.py`
    proxy_set_header X-Forwarded-Host $host;

    # [`SECURE_PROXY_SSL_HEADER`](https://docs.djangoproject.com/en/6.0/ref/settings/#secure-proxy-ssl-header)
    # is set to `('HTTP_X_FORWARDED_PROTO', 'https')` in `backend/gutenberg/settings/docker_base.py`
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
