# This location is used for responses with the `X-Accel-Redirect` header from Django
location /@webapp-html/ {
    internal;
    alias /usr/share/nginx/gutenberg/webapp_html/;
    add_header Cache-Control "no-cache";
}

location /static/ {
    alias /usr/share/nginx/gutenberg/static/;
    gzip_static on;
    add_header Cache-Control "public";
}
