# Generated by Django 3.1.2 on 2020-11-16 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UNKNOWN', 'unknown'), ('INCOMING', 'incoming'), ('PENDING', 'pending'), ('PROCESSING', 'processing'), ('PRINTING', 'printing'), ('COMPLETED', 'completed'), ('CANCELED', 'canceled'), ('CANCELING', 'canceling'), ('ERROR', 'error')], default='UNKNOWN', max_length=10)),
                ('status_reason', models.TextField(blank=True, max_length=2000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrintingProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.BooleanField(default=False)),
                ('copies', models.IntegerField(default=1)),
                ('two_sides', models.CharField(choices=[('OS', 'one sided'), ('TL', 'two sided long edge'), ('TS', 'two sided short edge')], default='OS', max_length=2)),
                ('pages_to_print', models.CharField(blank=True, max_length=100, null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='control.printjob')),
            ],
        ),
    ]
