# Generated by Django 3.1.4 on 2020-12-30 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('control', '0003_auto_20201230_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('printer_type', models.CharField(choices=[('NA', 'disabled'), ('LP', 'local cups')], default='NA', max_length=10)),
                ('color_supported', models.BooleanField(default=False)),
                ('duplex_supported', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='printjob',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LocalPrinterParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_grayscale_param', models.CharField(blank=True, max_length=64, null=True)),
                ('print_color_param', models.CharField(blank=True, max_length=64, null=True)),
                ('print_one_sided_param', models.CharField(blank=True, max_length=64, null=True)),
                ('print_two_sided_long_edge_param', models.CharField(blank=True, max_length=64, null=True)),
                ('print_two_sided_short_edge_param', models.CharField(blank=True, max_length=64, null=True)),
                ('printer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='control.printer')),
            ],
        ),
        migrations.AddField(
            model_name='printjob',
            name='printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.printer'),
        ),
        migrations.CreateModel(
            name='PrinterPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_color', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.printer')),
            ],
            options={
                'unique_together': {('printer', 'group')},
            },
        ),
    ]
