# Generated by Django 3.1.4 on 2020-12-31 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_auto_20201230_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='localprinterparams',
            name='cups_printer_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
