# Generated by Django 3.1.4 on 2020-12-31 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_localprinterparams_cups_printer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localprinterparams',
            name='cups_printer_name',
            field=models.CharField(default='invalid', max_length=128),
            preserve_default=False,
        ),
    ]
