# Generated by Django 3.1.4 on 2021-02-05 22:20

import control.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_auto_20201231_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingproperties',
            name='pages_to_print',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[control.models.validate_pages_to_print]),
        ),
    ]
