# Generated by Django 4.0.4 on 2022-04-15 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_auto_20220415_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobArtefact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='artefacts/%Y/%m/%d/')),
                ('artefact_type', models.CharField(choices=[('SC', 'source'), ('IN', 'intermediate'), ('FN', 'final')], default='SC', max_length=4)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.gutenbergjob')),
            ],
        ),
    ]
