# Generated by Django 5.2.4 on 2025-09-29 20:18

from django.db import migrations, models

import control.models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_printingproperties_fit_to_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingproperties',
            name='n_up',
            field=models.IntegerField(default=1, validators=[control.models.validate_n_up]),
        ),
    ]
