# Generated by Django 5.2.4 on 2025-09-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_printingproperties_fit_to_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobartefact',
            name='document_number',
            field=models.IntegerField(default=0),
        ),
    ]
