# Generated by Django 5.2.4 on 2025-09-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0013_jobartefact_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='gutenbergjob',
            name='next_document_number',
            field=models.IntegerField(default=1),
        ),
    ]
