# Generated by Django 5.2.4 on 2025-09-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0013_printingproperties_n_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingproperties',
            name='imposition_template',
            field=models.CharField(choices=[('none', 'none'), ('booklet', 'booklet')], default='none'),
        ),
    ]
