# Generated by Django 5.2.6 on 2025-10-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0014_printingproperties_imposition_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingproperties',
            name='orientation_requested',
            field=models.CharField(choices=[('AUTO', 'auto'), ('PORTRAIT', 'portrait'), ('LANDSCAPE', 'landscape')], default='AUTO'),
        ),
    ]
