# Generated by Django 5.2.6 on 2025-10-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0015_printingproperties_orientation_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='gutenbergjob',
            name='next_document_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jobartefact',
            name='document_number',
            field=models.IntegerField(default=0),
        ),
    ]
