# Generated by Django 6.0.7 on 2026-07-28 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0016_gutenbergjob_next_document_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gutenbergjob',
            name='configuration_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='PrintPreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('ready', 'ready'), ('failed', 'failed'), ('canceled', 'canceled')], default='pending', max_length=16)),
                ('generation', models.PositiveIntegerField(default=1)),
                ('configuration_version', models.PositiveIntegerField()),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preview', to='control.gutenbergjob')),
            ],
        ),
        migrations.CreateModel(
            name='PrintPreviewPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('image', models.FileField(upload_to='previews/%Y/%m/%d/')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('preview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='control.printpreview')),
            ],
            options={
                'ordering': ['number'],
                'constraints': [models.UniqueConstraint(fields=('preview', 'number'), name='unique_preview_page_number')],
            },
        ),
    ]
