# Generated by Django 6.0.7 on 2026-08-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0016_gutenbergjob_next_document_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
