# Generated by Django 6.0.7 on 2026-08-04 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0017_gutenbergjob_configuration_version_printpreview_and_more'),
        ('control', '0017_printer_display_order'),
    ]

    operations = []
