# Generated by Django 6.0.7 on 2026-08-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0018_merge_20260804_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='gutenbergjob',
            name='manual_duplex_current_pass',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='localprinterparams',
            name='manual_duplex_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='localprinterparams',
            name='manual_duplex_face_orientation',
            field=models.CharField(choices=[('UP', 'face up'), ('DOWN', 'face down')], default='UP', max_length=4),
        ),
        migrations.AddField(
            model_name='localprinterparams',
            name='manual_duplex_feed_edge',
            field=models.CharField(choices=[('LONG', 'long edge'), ('SHORT', 'short edge')], default='LONG', max_length=5),
        ),
        migrations.AddField(
            model_name='localprinterparams',
            name='manual_duplex_first_pass',
            field=models.CharField(choices=[('ODD', 'odd pages first'), ('EVEN', 'even pages first')], default='ODD', max_length=4),
        ),
        migrations.AddField(
            model_name='localprinterparams',
            name='manual_duplex_first_pass_reverse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='localprinterparams',
            name='manual_duplex_second_pass_reverse',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gutenbergjob',
            name='status',
            field=models.CharField(choices=[('UNKNOWN', 'unknown'), ('INCOMING', 'incoming'), ('PENDING', 'pending'), ('PROCESSING', 'processing'), ('PRINTING', 'printing'), ('WAITING_ACT', 'waiting for user action'), ('COMPLETED', 'completed'), ('CANCELED', 'canceled'), ('CANCELING', 'canceling'), ('ERROR', 'error')], default='UNKNOWN', max_length=12),
        ),
        migrations.AlterField(
            model_name='printer',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Printers are displayed in ascending order. Lower values appear first. The first printer in the list is used as the default.'),
        ),
        migrations.AlterField(
            model_name='printpreviewpage',
            name='height',
            field=models.PositiveIntegerField(help_text='Preview image height in pixels'),
        ),
        migrations.AlterField(
            model_name='printpreviewpage',
            name='width',
            field=models.PositiveIntegerField(help_text='Preview image width in pixels'),
        ),
    ]
