# Generated by Django 6.1 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0018_merge_20260804_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='availability',
            field=models.CharField(
                choices=[('AVAILABLE', 'available'), ('MAINTENANCE', 'under maintenance')],
                default='AVAILABLE',
                help_text='Maintenance printers stay visible to users but cannot accept new jobs.',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='printer',
            name='maintenance_message',
            field=models.CharField(
                blank=True,
                help_text='Optional message displayed to users while this printer is under maintenance.',
                max_length=240,
            ),
        ),
    ]
