# Generated by Django 6.0.7 on 2026-08-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0019_groupquota_userquotaoverride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='display_order',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Printers are displayed in ascending order. Lower values appear first. The first printer in the list is used as the default.',
            ),
        ),
        migrations.AlterField(
            model_name='printpreviewpage',
            name='height',
            field=models.PositiveIntegerField(help_text='Preview image height in pixels'),
        ),
        migrations.AlterField(
            model_name='printpreviewpage',
            name='width',
            field=models.PositiveIntegerField(help_text='Preview image width in pixels'),
        ),
    ]
