# Generated by Django 6.0.7 on 2026-08-20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0020_alter_printer_display_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly')], max_length=8)),
                ('period_start', models.DateField()),
                ('reserved_impressions', models.PositiveIntegerField(default=0)),
                ('charged_impressions', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'period', 'period_start'), name='unique_user_quota_period')],
            },
        ),
        migrations.CreateModel(
            name='QuotaReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impressions', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('reserved', 'reserved'), ('charged', 'charged'), ('released', 'released')], default='reserved', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_reservations', to='control.gutenbergjob')),
                ('usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.quotausage')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job', 'usage'), name='unique_job_quota_usage')],
            },
        ),
    ]
