# Generated by Django 3.1.2 on 2020-12-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printjob',
            old_name='date',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='printjob',
            name='date_finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='date_processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
