# Generated by Django 3.1.4 on 2020-12-30 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control', '0002_auto_20201216_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printjob',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='status_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
