# Generated by Django 3.2.7 on 2022-04-15 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control', '0007_auto_20210205_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='GutenbergJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('job_type', models.CharField(choices=[('NA', 'unknown'), ('PRINT', 'print')], default='NA', max_length=10)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UNKNOWN', 'unknown'), ('INCOMING', 'incoming'), ('PENDING', 'pending'), ('PROCESSING', 'processing'), ('PRINTING', 'printing'), ('COMPLETED', 'completed'), ('CANCELED', 'canceled'), ('CANCELING', 'canceling'), ('ERROR', 'error')], default='UNKNOWN', max_length=12)),
                ('status_reason', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_processed', models.DateTimeField(blank=True, null=True)),
                ('date_finished', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.printer')),
            ],
        ),
        migrations.AlterField(
            model_name='printingproperties',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='control.gutenbergjob'),
        ),
        migrations.DeleteModel(
            name='PrintJob',
        ),
    ]
