# Generated by Django 5.2.4 on 2025-08-10 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_printingproperties_fit_to_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printingproperties',
            name='job',
        ),
        migrations.AddField(
            model_name='printingproperties',
            name='artefact',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='control.jobartefact'),
            preserve_default=False,
        ),
    ]
