name: Gutenberg

on: [push]

jobs:
  test_django:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: gutenberg.settings.test_settings
    steps:
    - uses: actions/checkout@v2
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: 'pyproject.toml'
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.8.2"
    - name: Configure venv and install dependencies
      run: uv sync
    - name: Run migrations
      run: uv run manage.py migrate
    - name: Run tests
      run: uv run manage.py test

  test_webapp:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x, lts/*, latest]
    steps:
    - uses: actions/checkout@v5
      with:
        sparse-checkout: |
          .github
          webapp
    - name: Use Node.js version ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      working-directory: webapp
      run: pnpm install --frozen-lockfile
    - name: Build
      working-directory: webapp
      run: pnpm run build
